Web/Web/Controllers/MARKETINGController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Web.Business;
using Web.Messages;
using Web.Models;
using Web.Utils;

namespace Web.Controllers
{
    public class MARKETINGController : Controller
    {
        private SmartBagEntities db = new SmartBagEntities();

        #region private Helpers
        private void ComboStatus(bool? active = null)
        {
            List<SelectListItem> lista = new List<SelectListItem>();

            lista.Add(new SelectListItem { Value = "1", Text = "Ativo" });
            lista.Add(new SelectListItem { Value = "0", Text = "Inativo" });
            if (active == null)
                ViewBag.Status = new SelectList(lista, "Value", "Text");
            else
            { 
                if (active.Value)
                    ViewBag.Status = new SelectList(lista, "Value", "Text", "1");
                else
                    ViewBag.Status = new SelectList(lista, "Value", "Text", "0");
            }
        }
        private string GetTipoArquivo(string formato)
        {
            string tipo = "";
            switch (formato.ToUpper())
            { 
                case ".MP4":
                case ".AVI":
                case ".MPEG":
                case ".MPG":
                    tipo = "VID";
                    break;
                case ".JPG":
                case ".JPEG":
                case ".PNG":
                case ".BMP":
                    tipo = "IMG";
                    break;
                default:
                    tipo = "DIF";
                    break;
            }
            return tipo;
        }
        private void SaveFTP(HttpPostedFileBase file, int CodMarketing, string ArquivoAntigo)
        {
            #region deleteOldFile
            if (!string.IsNullOrEmpty(ArquivoAntigo))
            {
                try {
                    string DEL_URIString = ParametrosBLL.GetParameter("FTPServer") + "/" + ParametrosBLL.GetParameter("FTPMarketing") + "/" + ArquivoAntigo;
                    FtpWebRequest DEL_request = (FtpWebRequest)WebRequest.Create(DEL_URIString);
                    DEL_request.Credentials = new NetworkCredential(ParametrosBLL.GetParameter("FTPUser"), ParametrosBLL.GetParameter("FTPPwd"));
                    DEL_request.Method = WebRequestMethods.Ftp.DeleteFile;
                    FtpWebResponse DEL_response = (FtpWebResponse)DEL_request.GetResponse();
                    Console.WriteLine("Delete status: {0}", DEL_response.StatusDescription);
                    DEL_response.Close();
                }
                catch (Exception)
                { }

            }
            #endregion

            string fileName = CodMarketing.ToString() + "_" + Path.GetFileName(file.FileName);
            string URIString = ParametrosBLL.GetParameter("FTPServer") + "/" + ParametrosBLL.GetParameter("FTPMarketing") + "/" + fileName;
            FtpWebRequest request = (FtpWebRequest)WebRequest.Create(URIString);
            request.Method = WebRequestMethods.Ftp.UploadFile;

            request.Credentials = new NetworkCredential(ParametrosBLL.GetParameter("FTPUser"), ParametrosBLL.GetParameter("FTPPwd"));

            var sourceStream = file.InputStream;
            Stream requestStream = request.GetRequestStream();
            request.ContentLength = sourceStream.Length;
            byte[] buffer = new byte[file.ContentLength];
            int bytesRead = sourceStream.Read(buffer, 0, file.ContentLength);
            do
            {
                requestStream.Write(buffer, 0, bytesRead);
                bytesRead = sourceStream.Read(buffer, 0, file.ContentLength);
            } while (bytesRead > 0);
            sourceStream.Close();
            requestStream.Close();
            FtpWebResponse response = (FtpWebResponse)request.GetResponse();

        }
        #endregion

        #region Index/Pesquisa
        public ActionResult Index()
        {
            ComboStatus(true);
            ViewBag.TipoMarketing = new SelectList(db.TBT_TIPO_MARKETING, "CodTipoMarketing", "Descricao");
            MarketingBLL BLL = new MarketingBLL();
            var ListaConsulta = BLL.SearchMarketing(1, null, null, null);
            return View(ListaConsulta);
        }
        public ActionResult Pesquisa([Bind(Include = "Status, TipoMarketing, Descricao, Titulo")] int? Status, int? TipoMarketing, string Descricao, string Titulo)
        {
            ComboStatus();
            ViewBag.TipoMarketing = new SelectList(db.TBT_TIPO_MARKETING, "CodTipoMarketing", "Descricao");

            MarketingBLL BLL = new MarketingBLL();

            var ListaConsulta = BLL.SearchMarketing(Status, TipoMarketing, Descricao, Titulo);

            return PartialView("_PartialMarketing", ListaConsulta);
        }
        #endregion

        #region Edição
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MarketingBLL BLL = new MarketingBLL();
            Marketing tBT_Marketing = BLL.GetMarketing(id);

            if (tBT_Marketing == null)
            {
                return HttpNotFound();
            }
            ComboStatus(tBT_Marketing.Ativo);
            ViewBag.CodTipoMarketing = new SelectList(db.TBT_TIPO_MARKETING, "CodTipoMarketing", "Descricao", tBT_Marketing.CodTipoMarketing);
            ViewBag.CodMarca = new SelectList(db.TBT_MARCA, "CodMarca", "Descricao", tBT_Marketing.CodMarca);
            return View(tBT_Marketing);
        }
        // POST: TBT_USER/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Status, Arquivo, Titulo, Descricao, CodTipoMarketing, CodMarca")] int Status, HttpPostedFileBase Arquivo, Marketing MKT)
        {
            MarketingBLL BLL = new MarketingBLL();
            Marketing OldMarketing = BLL.GetMarketing(MKT.CodMarketing);
            string ArquivoAntigo = OldMarketing.NomeArquivo;
            string TipoARquivoAntigo = OldMarketing.TipoArquivo;
            MKT.Ativo = Status == 1;
            if (ModelState.IsValid)
            {
                if (Arquivo != null && Arquivo.ContentLength > 0)
                {
                    var fileName = MKT.CodMarketing.ToString() + "_" + Path.GetFileName(Arquivo.FileName);
                    string fileExtension = System.IO.Path.GetExtension(fileName);
                    MKT.NomeArquivo = fileName;
                    MKT.TipoArquivo = GetTipoArquivo(fileExtension);
                }
                else
                {
                    MKT.NomeArquivo = ArquivoAntigo;
                    MKT.TipoArquivo = TipoARquivoAntigo;
                }
                bool saved = BLL.SaveEdit(MKT);
                if (saved)
                {
                    if (Arquivo != null && Arquivo.ContentLength > 0)
                    {
                        try
                        {
                            SaveFTP(Arquivo, MKT.CodMarketing, ArquivoAntigo);
                        }
                        catch(Exception)
                        {
                            TempData["Marketing"] = "Failure";
                            TempData["Message"] = "Ocorreu um erro ao tentar salvar o arquivo do marketing no servidor FTP.";
                            return RedirectToAction("Index");
                        }
                        
                    }
                    TempData["Marketing"] = "Success";
                    TempData["Message"] = "Marketing editado com sucesso!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Marketing"] = "Failure";
                    TempData["Message"] = "Ocorreu um erro ao tentar salvar o marketing.";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["Marketing"] = "Failure";
                TempData["Message"] = "Ocorreu um erro ao tentar salvar o marketing.";
                return RedirectToAction("Index");
            }
        }
        #endregion


        // GET: TBT_USER/Create
        public ActionResult Create()
        {
            ViewData["errovalidation"] = "";
            ViewData["sucessovalidation"] = "";

            ViewBag.CodTipoMarketing = new SelectList(db.TBT_TIPO_MARKETING, "CodTipoMarketing", "Descricao");
            ViewBag.CodMarca = new SelectList(db.TBT_MARCA, "CodMarca", "Descricao", "1");
            return View();
        }

        // POST: TBT_USER/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Arquivo, Titulo, Descricao, CodTipoMarketing, CodMarca")] HttpPostedFileBase Arquivo, Marketing MKT)
        {
            MarketingBLL BLL = new MarketingBLL();
            MKT.Ativo = true;
            MKT = BLL.IncluirMkt(MKT);
            if (Arquivo != null && Arquivo.ContentLength > 0)
            {
                var fileName = MKT.CodMarketing.ToString() + "_" + Path.GetFileName(Arquivo.FileName);
                string fileExtension = System.IO.Path.GetExtension(fileName);
                MKT.NomeArquivo = fileName;
                MKT.TipoArquivo = GetTipoArquivo(fileExtension);
            }
            

Web/Web/Views/MARKETING/Create.cshtml
@model Web.Messages.Marketing

<div class="wrapper row-offcanvas row-offcanvas-left" style="margin-left: 15px; margin-top: -50px">
    <!-- Right side column. Contains the navbar and content of the page -->
    <aside class="right-side">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Criar Marketing
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Marketing</li>
                <li class="active">Criar</li>
            </ol>
        </section>
        @htmlHelpers.HelperConfirmation(TempData["Marketing"], TempData["Message"])
        @using (Html.BeginForm("Create", "MARKETING", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(true)
            @Html.AntiForgeryToken()
          <!-- Main content -->
        <section class="content invoice">
            <div class="row">
                <!-- accepted payments column -->
                <div class="col-xs-6">
                    <div class="box-body">

                        <div class="form-group">
                            <label>Título</label>
                            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        </div>

                        <div class="form-group">
                            <label>Tipo de Marketing</label>
                            @Html.DropDownList("CodTipoMarketing", null, "-- Selectione um Tipo--", htmlAttributes: new { @class = "form-control", @required = "required" })
                        </div>

                        <div class="form-group">
                            <label>Marca</label>
                            @Html.DropDownList("CodMarca", null, "-- Selectione uma Marca--", htmlAttributes: new { @class = "form-control", @required = "required" })
                        </div>
                        <br />
                    </div><!-- /.box-body -->
                </div><!-- /.col -->
                <div class="col-xs-6">
                    <div class="box-body">

                        <div class="form-group">
                            <label>Descrição</label>
                            @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control", @required = "required" })
                        </div>

                        <div class="form-group">
                            <label>Arquivo</label>
                            <input type="file" name="Arquivo" id="Arquivo" class="form-control" />
                        </div>

                        <br />
                    </div><!-- /.box-body -->
                </div><!-- /.col -->
            </div><!-- /.row -->
            <div class="row">
            </div>

            <div class="col-xs-12">
                <a href="~/MARKETING/Index"><i class="fa fa-toggle-left"></i> Back</a>
                <button class="btn btn-success pull-right"><i class="fa fa-check-square-o"></i> Salvar</button>
            </div>
        </section><!-- /.content -->
        }
    </aside><!-- /.right-side -->
</div><!-- ./wrapper -->
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#Titulo").attr('maxlength', '100');
            $("#Descricao").attr('maxlength', '200');
        });
    </script>
}   

Web/Web/Views/MARKETING/Edit.cshtml
@model Web.Messages.Marketing

<body class="skin-black">
    <!-- header logo: style can be found in header.less -->

    <div class="wrapper row-offcanvas row-offcanvas-left" style="margin-left: 15px; margin-top: -50px">

        <!-- Right side column. Contains the navbar and content of the page -->
        <aside class="right-side">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Editar Marketing
                </h1>
                <ol class="breadcrumb">
                    <li><a href="~/Home/Inicio"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li class="active">Marketing</li>
                    <li class="active">Edit</li>
                </ol>
            </section>
            @htmlHelpers.HelperConfirmation(TempData["Marketing"], TempData["Message"])

            @using (Html.BeginForm("Edit", "MARKETING", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.CodMarketing)
            <!-- Main content -->
                <section class="content invoice">
                    <div class="row">
                        <!-- accepted payments column -->
                        <div class="col-xs-6">
                                <div class="box-body">

                                    <div class="form-group">
                                        <label>Título</label>
                                        @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                        @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        <label>Tipo de Marketing</label>
                                        @Html.DropDownList("CodTipoMarketing", null, "-- Selectione um Tipo--", htmlAttributes: new { @class = "form-control", @required = "required" })
                                    </div>

                                    <div class="form-group">
                                        <label>Status</label>
                                        @Html.DropDownList("Status", null, "-- Selectione um status--", htmlAttributes: new { @class = "form-control", @required = "required" })
                                    </div>

                                    <div class="form-group">
                                        <label>Marca</label>
                                        @Html.DropDownList("CodMarca", null, "-- Selectione uma Marca--", htmlAttributes: new { @class = "form-control", @required = "required" })
                                    </div>
                                    <br />
                                </div><!-- /.box-body -->
                        </div><!-- /.col -->
                        <div class="col-xs-6">
                                <div class="box-body">

                                    <div class="form-group">
                                        <label>Descrição</label>
                                        @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control", @required = "required" })
                                        @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        <label>Arquivo</label>
                                        <input type="file" name="Arquivo" id="Arquivo" class="form-control" />
                                    </div>

                                    <br />
                                </div><!-- /.box-body -->
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                    <div class="row">
                    </div>

                    <div class="col-xs-12">
                        <a href="~/MARKETING/Index"><i class="fa fa-toggle-left"></i> Back</a>
                        <button class="btn btn-success pull-right"><i class="fa fa-check-square-o"></i> Salvar</button>
                    </div>
                </section><!-- /.content -->
            }
        </aside><!-- /.right-side -->
    </div><!-- ./wrapper -->
</body>

@section scripts
{
    <script type="text/javascript">
            $(document).ready(function () {
                $("#Titulo").attr('maxlength', '100');
                $("#Descricao").attr('maxlength', '200');
            });
    </script>
}   

Web/Web/Views/MARKETING/Index.cshtml
@model  List<Web.Messages.Marketing>
@using PagedList.Mvc;

    <!-- header logo: style can be found in header.less -->
    <div class="wrapper row-offcanvas row-offcanvas-left" style="margin-left: 15px; margin-top: -50px">

        <!-- Right side column. Contains the navbar and content of the page -->
        <aside class="right-side">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Pesquisar Marketing
                </h1>
                <ol class="breadcrumb">
                    <li><a href="~/Home/Inicio"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li class="active">Marketing</li>
                    <li class="active">Pesquisa</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="row">
                    <div class="col-md-6">
                        <!-- /.box --><!-- /.box -->
                    </div><!-- /.col -->
                    <div class="col-md-6">
                        <!-- /.box --><!-- /.box -->
                    </div><!-- /.col -->
                </div>

                @htmlHelpers.HelperConfirmation(TempData["Marketing"], TempData["Message"])

                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">
                                    <img id="Right" onclick="showHide('menu'); return false;" src="~/Content/Imagens/RightArrow.png" />
                                    <img id="Down" onclick="showHide('menu'); return false;" src="~/Content/Imagens/DownArrow.png" style="display: none" />
                                    Filtros
                                </h3>
                                <div class="box-tools">
                                    <div style="float: right;">
                                        <form action="~/MARKETING/Create"><button type="submit" class="btn btn-primary">Novo</button></form>
                                    </div>
                                </div>
                            </div><!-- /.box-header -->
                            @using (Ajax.BeginForm("Pesquisa", "MARKETING", new AjaxOptions
                            {
                                HttpMethod = "GET",
                                InsertionMode = InsertionMode.Replace,
                                UpdateTargetId = "_PartialMarketing"

                            }))
                            {
                                <div class="row" id="menu" style="display: none;">
                                    <!-- accepted payments column -->
                                    <div class="col-xs-6">
                                        <div role="form">
                                            <div class="box-body">
                                                <div class="form-group">
                                                    <label>Título</label>
                                                    @Html.TextBox("Titulo", "", htmlAttributes: new { @class = "form-control" })
                                                </div>

                                                <div class="form-group">
                                                    <label>Tipo de Marketing</label>
                                                    @Html.DropDownList("TipoMarketing", null, "--Selecione um Tipo--", htmlAttributes: new { @class = "form-control", id = "TipoMarketing" })
                                                </div>
                                                <div class="form-group">
                                                    <button class="btn btn-primary" id="pesquisar" onclick="showHide('menu');">Search</button>
                                                </div>

                                            </div><!-- /.box-body -->
                                        </div>
                                    </div><!-- /.col -->
                                    <div class="col-xs-6">
                                        <form role="form">
                                            <div class="box-body">
                                                <div class="form-group">
                                                    <label>Descrição</label>
                                                    @Html.TextArea("Descricao", "", htmlAttributes: new { @class = "form-control" })
                                                </div>
                                                <div class="form-group">
                                                    <label>Status</label>
                                                    @Html.DropDownList("Status", null, "--Selecione um Status--", htmlAttributes: new { @class = "form-control", id = "TipoMarketing" })
                                                </div>
                                            </div><!-- /.box-body -->
                                        </form>
                                    </div><!-- /.col -->
                                </div><!-- /.row -->
                            }
                        </div><!-- /.Fim dos Filtros<-->
                    </div>
                </div>
                <div id="_PartialMarketing">
                    @Html.Partial("_PartialMarketing", Model)
                </div>
            </section><!-- /.content -->
        </aside><!-- /.right-side -->
    </div><!-- ./wrapper -->
    @section scripts
    {

        <script type="text/javascript">
            function showHide(obj) {
                var div = document.getElementById(obj);
                if (div.style.display == 'none') {
                    div.style.display = '';
                    document.getElementById('Down').style.display = '';
                    document.getElementById('Right').style.display = 'none';
                }
                else {
                    div.style.display = 'none';
                    document.getElementById('Down').style.display = 'none';
                    document.getElementById('Right').style.display = '';
                }
            }
        </script>





    }

Web/Web/Views/MARKETING/_PartialMarketing.cshtml
@model  List<Web.Messages.Marketing>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

<!-- /.row -->
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="row">
                    <div class="col-md-8">
                        <h3 class="box-title">Pesquisa de Marketing</h3>
                    </div>
                    <div class="box-tools"></div>
                    <div class="col-md-3 navbar-right text-right results_Found">
                        @Model.Count resultados encontrados
                    </div>

                </div>
            </div>
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tr>
                        <th>Tipo</th>
                        <th>Status</th>
                        <th>Título</th>
                        <th>Descricao</th>
                        <th>Nome do Arquivo</th>
                        <th>Data de Cadastro</th>
                        <th>Editar</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.TipoMarketing)
                            </td>
                            <td>
                                @Functions.Status(item.Ativo)
                            </td>
                            <td>
                                @Functions.Chop(@Html.DisplayFor(modelItem => item.Titulo).ToString(),20)
                            </td>
                            <td>
                                @Functions.Chop(@Html.DisplayFor(modelItem => item.Descricao).ToString(), 20)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NomeArquivo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DataCadastro)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.CodMarketing })
                            </td>
                        </tr>
                    }
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div>
</div>